FROM network-inspector_infra as infra

WORKDIR /network-inspector/web

COPY ./web/server/package.json ./web/server/package-lock.json ./server/

COPY ./web/app/package.json ./web/app/package-lock.json ./app/

RUN pip install lxml=="4.9.2" beautifulsoup4=="4.12.2"

RUN cd ./server && npm ci && cd ../app && npm ci


FROM infra

WORKDIR /network-inspector

COPY . .
COPY --from=infra /network-inspector/web ./web

RUN chmod +x ./setup.sh

EXPOSE 3000
EXPOSE 80