version: '3.8'

services:
  infra:
    build:
      context: . 
      dockerfile: Dockerfile.infra 

  script:
    build:
      context: . 
      dockerfile: Dockerfile.script 
    depends_on:
      - infra
